matrix:
  include:
    - language: node_js
      node_js: 12
      before_install:
        - cd frontend
      install:
        - npm i
      script:
        - npm run test
    
    - language: python
      python: 3.7.4
      install:
        - pip install -r requirements.txt
      script:
        - python ./backend/manage.py test meals
      