version: "3.7"

services:
    frontend:
        build:
            context: "frontend/"
            target: builder
        working_dir: /code/frontend
        command: sh /code/frontend/entrypoint.sh
        volumes:
            - frontend:/code/frontend/node_modules
            - ./frontend:/code/frontend
        networks:
            - nginx_network
        stdin_open: true

    djangoapp:
        build: .
        command:
            [
                "./wait-for-it.sh",
                "database1:5432",
                "--",
                "python",
                "manage.py",
                "runserver",
                "0.0.0.0:8000",
            ]
        env_file:
            - config/db/database1_env
        volumes:
            - ./backend:/code
        ports:
            - 8000:8000
        networks:
            - nginx_network
            - database1_network
        depends_on:
            - database1
            - frontend

    nginx:
        image: nginx:1.17
        ports:
            - 3000:80
        volumes:
            - ./config/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - frontend
            - djangoapp
        networks:
            - nginx_network

    database1:
        image: postgres:10
        env_file:
            - config/db/database1_env
        networks:
            - database1_network
        volumes:
            - database1_volume:/var/lib/postgresql/data
        ports:
            - 5432:5432

networks: # <-- and here
    nginx_network:
        driver: bridge
    database1_network: # <-- add the bridge
        driver: bridge

volumes:
    database1_volume:
    frontend:
