# Generated by Django 3.0 on 2019-12-23 22:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.DateField(default=datetime.datetime(2019, 12, 23, 22, 20, 59, 247176, tzinfo=utc)),
        ),
    ]
