# Generated by Django 3.0.5 on 2020-05-03 19:42

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_auto_20191223_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='meals.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 19, 42, 51, 31514, tzinfo=utc)),
        ),
    ]
