# Generated by Django 3.0.5 on 2020-05-03 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_auto_20200503_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 19, 58, 4, 78539, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time_of_day',
            field=models.IntegerField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')]),
        ),
    ]
