# Generated by Django 3.0.5 on 2020-05-03 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20200503_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 5, 3, 20, 0, 35, 661838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time_of_day',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=100),
        ),
    ]
