# Generated by Django 3.0.6 on 2020-05-28 01:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0005_auto_20200503_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='created',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='updated',
        ),
        migrations.AlterField(
            model_name='food',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_in_meal', to='meals.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 5, 28, 1, 58, 48, 892732, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_food', to='meals.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
