# Generated by Django 3.0.6 on 2020-05-28 03:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_auto_20200528_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='day',
            field=models.DateField(default=datetime.datetime(2020, 5, 28, 3, 34, 31, 866326, tzinfo=utc)),
        ),
    ]
